"""empty message

Revision ID: f5ca1e7fe27e
Revises: 1fd502f6adcf
Create Date: 2024-05-16 10:32:19.912413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ca1e7fe27e'
down_revision = '1fd502f6adcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_table_doctor_id_doctors_table'), 'doctors_table', ['doctor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appointments_table_patient_id_patients_table'), 'patients_table', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_table_patient_id_patients_table'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appointments_table_doctor_id_doctors_table'), type_='foreignkey')
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
